mediacloud/web-tools

README.md

This is a test commit to see how the GitHub flow for closing off branches works

pull request to close off branch

---

server/views/sources/collection.py

If the user enters an invalid pub_state in the css doc, it will fail to
add the value

#260 better comparison for pub_state values e.g. ###_##

---

server/util/csv.py
server/util/tags.py
server/views/sources/__init__.py
server/views/sources/collectionedit.py
server/views/sources/source.py
src/actions/sources/metadataActions.js
src/components/common/IntlForm.js
src/components/common/MetadataPickerContainer.js
src/components/source/mediaSource/CreateSourceContainer.js
src/components/source/mediaSource/EditSourceContainer.js
src/components/source/mediaSource/form/SourceMetadataForm.js
src/components/source/search/AdvancedSearchContainer.js
src/components/source/search/AdvancedSearchForm.js
src/lib/serverApi/sources.js
src/reducers/system/metadata/mediaType.js
src/reducers/system/metadata/metadata.js

Got MenuItem working with just primaryText and <br />s. Need to style

Feature media type - editable

---

server/views/media_picker.py
src/actions/system/mediaPickerActions.js
src/components/common/mediaPicker/MediaPickerResultsContainer.js
src/components/common/mediaPicker/MediaPickerSearchForm.js
src/components/common/mediaPicker/results/CollectionSearchResultsContainer.js
src/components/common/mediaPicker/results/SourceSearchResultsContainer.js
src/reducers/system/mediaPicker/media.js

note: retrieving the same collection- e.g. Search By Country->Featured and Search By Collections->”mainstream” does not correctly update the selected status of something like U.S. Mainstream collection

Feature explorer media picker #749

---

src/components/topic/snapshots/foci/CreateFocusContainer.js
src/components/topic/snapshots/foci/builder/FocusForm3DescribeContainer.js
src/components/topic/snapshots/foci/builder/FocusForm4ConfirmContainer.js

but the validation error isn’t showing up

#595 validate focal set name during form and before save

---

src/components/explorer/UrlBasedQueryContainer.js
src/components/explorer/builder/DemoQueryContainer.js
src/components/explorer/builder/QueryPicker.js
src/components/explorer/builder/QueryPickerLoadUserSearchesDialog.js
src/components/explorer/home/Homepage.js
src/lib/explorerUtil.js
src/reducers/explorer/queries/queries.js
src/reducers/explorer/selected.js
src/styles/explorer/_saved_searches.scss

Feature explorer search handling

---

src/components/topic/FilteredTopicContainer.js
src/components/topic/controlbar/TopicFilterControlBar.js
src/lib/urlUtil.js
src/styles/topics/_controlbar.scss

Adds a new link to the topic homepage.  Similar explorer link is inactive for now (due to #846 )

Add "query on dashboard" link to topic control bar

---

server/views/topics/foci/retweetpartisanship.py
src/components/topic/snapshots/foci/builder/retweetPartisanship/RetweetStoryCountsPreviewContainer.js
src/components/topic/summary/NytLabelSummaryContainer.js
src/components/vis/BubbleRowChart.js
src/styles/explorer/_bubble_chart.scss
src/styles/explorer/explorer.scss
src/styles/viz/_bubble_chart.scss

improve subtopic retweet partisanship generation & viz

---

server/views/sources/collectionedit.py

This adds utf8 "http://" to sources uploaded via CSV.
Also it adds a new pool for creating the media in chunks to try and speed it up via parallelization.
(#977, #978)

media upload improvements

---

src/components/common/form/SourceCollectionsMediaForm.js
src/components/common/mediaPicker/MediaPickerDialog.js
src/components/topic/create/EditTopicContainer.js
src/components/topic/create/TopicForm.js
src/reducers/system/mediaPicker/selectMedia.js

Only remaining issue is that the pristine flag is not set to false when the sub-form sourcesAndCollections is modified

Fix topic edit and mediapicker selection

---

package-lock.json
package.json
server/__init__.py
server/templates/index.html
src/index.js
src/reducers/user.js
src/store.js

maybe tweak some more depending on what we want to isolate?

Feature raven sentry for js

---

src/components/topic/list/PersonalTopicsContainer.js
src/components/topic/list/PublicTopicsContainer.js
src/components/topic/list/TopicListContainer.js
src/components/topic/list/TopicPreviewList.js
src/components/topic/summary/TopicSummaryContainer.js

use Grid to make Rows and Columns behave uniformly regardless of result set

#1194 and #1180

---

src/components/common/hocs/CsvDownloadNotifyContainer.js
src/components/common/hocs/SaveableContainer.js
src/components/explorer/builder/QueryPicker.js
src/components/explorer/results/drilldowns/WordInContextDrillDownContainer.js
src/components/source/SourceMgrHeaderContainer.js
src/components/source/collection/CollectionUploadSourceContainer.js
src/components/source/collection/CreateCollectionContainer.js
src/components/source/collection/EditCollectionContainer.js
src/components/source/collection/ManageSourcesContainer.js
src/components/source/collection/form/CollectionMediaForm.js
src/components/source/mediaSource/CreateSourceContainer.js
src/components/source/mediaSource/CreateSourceFeedContainer.js
src/components/source/mediaSource/EditSourceContainer.js
src/components/source/mediaSource/EditSourceFeedContainer.js
src/components/source/mediaSource/SourceFeedContainer.js
src/components/source/mediaSource/suggest/SuggestSourceContainer.js
src/components/topic/controlbar/TopicFilterControlBar.js

we already have the topics updated

#1225 sources and explorer feedback update

---

server/views/topics/media.py
server/views/topics/stories.py
src/components/topic/TopicOwnerList.js
src/components/topic/controlbar/TopicInfo.js
src/components/topic/list/TopicPreviewList.js
src/components/topic/media/MediaInlinkContainer.js
src/components/topic/media/MediaInlinkTableContainer.js
src/components/topic/media/MediaInlinkTreeMapContainer.js
src/components/topic/media/MediaOutlinkContainer.js
src/components/topic/media/MediaOutlinkTableContainer.js
src/components/topic/media/MediaOutlinkTreeMapContainer.js
src/components/vis/TreeMap.js
src/reducers/topics/selected/mediaSource/allInlinks.js
src/reducers/topics/selected/mediaSource/allOutlinks.js
src/reducers/topics/selected/mediaSource/mediaSource.js

Plus a small tweak to show topic owners in the popup about topic dialog

Topic media inlink/outlink tree map fixes

---

server/views/topics/topic.py
src/components/common/AppButton.js
src/components/common/PageTitle.js
src/components/common/form/Autocomplete.js
src/components/common/header/TopicsAppMenu.js
src/components/topic/homepage/TopicsHomepage.js
src/components/topic/list/TopicPreviewList.js
src/components/topic/media/InfluentialMediaContainer.js
src/components/topic/media/MediaSearchContainer.js
src/components/topic/search/MatchingTopicsContainer.js
src/components/topic/search/TopicQuickSearchContainer.js
src/components/topic/search/TopicSearchContainer.js
src/components/topic/search/TopicSearchForm.js
src/lib/reactUtil.js
src/lib/serverApi/topics.js
src/routes/topicRoutes.js
src/styles/app/_tab_selector.scss
src/styles/topics/_controlbar.scss
src/styles/topics/_topic_list.scss
src/styles/topics/_topic_search.scss

Adds new `Autocomplete` and `AsyncAutocomplete` widgets (based on `react-select`) to use on topic search, with a link to a real topic search page.

Feature topics better search

---

src/components/explorer/results/QueryTopEntitiesPeopleResultsContainer.js

@rahulbot / @cindyloo -- noticed this spelling error while using Explorer.

Fix spelling

---

src/components/vis/BubbleRowChart.js
src/components/vis/PackedBubbleChart.js

Hi Rahul
Sorry for the previous stuff. This is much tidier.
thanks -- Rick

fix bad syntax for some !important rules

---

README.md

@rahulbot / @cindyloo -- `config/server.config.template` does not exist. Is the proposed change in this PR correct?

Update config readme

---

src/components/topic/controlbar/CreateSnapshotButton.js

I just noticed this misspelling ("fronzen").

Fix misspelling

---

src/components/source/SourceFeedTable.js
src/resources/messages.js

Annotate system generated spider feeds

---

src/components/explorer/results/QueryTotalAttentionResultsContainer.js

Added SVG download for Explorer attention bubble chart

---

src/components/common/SimpleDialog.js
src/components/common/hocs/HelpfulContainer.js

Refactored HelpfulContainer to use HelpDialog

---

src/components/common/header/AppNotice.js
src/components/common/news/RecentNewsItem.js
src/components/common/news/RecentNewsMenuItem.js
src/styles/app/_recent_news.scss

Replace dangerouslySetInnerHTML with SanitizedHTML

---

server/platforms/web_mediacloud.py
server/views/apicache.py
server/views/app.py
server/views/explorer/__init__.py
server/views/explorer/apicache.py
server/views/explorer/explorer_query.py
server/views/explorer/story_samples.py
server/views/explorer/tags.py
server/views/explorer/words.py
server/views/stories.py
server/views/topics/story.py
server/views/topics/topic.py

See #1842 for details on motivation.

Switch to user-agnostic cache for Explorer

---

doc/releases.md

I wanted to record the bug fix / patch process as it wasn't documented anywhere.

Document bug fix & patch release process

---

server/util/file.py
server/util/request.py
server/views/sources/collection.py
server/views/sources/collectionedit.py
server/views/topics/platforms/platforms_generic_csv.py

Fixes #1773
I tested this in the topics multiplatform csv upload and in the sources upload.

Refactored CSV validation and saving

---

.pylintrc
server/platforms/web_mediacloud.py
server/util/file.py
server/views/explorer/story_counts.py
server/views/sources/collectionedit.py
server/views/sources/source.py
server/views/topics/apicache.py
server/views/topics/files.py
server/views/topics/foci/focaldefs.py
server/views/topics/foci/focalsets.py
server/views/topics/foci/nyttheme.py
server/views/topics/topic.py
server/views/topics/topicsnapshot.py
server/views/topics/words.py
server/views/user.py

* Added underscore to unused tuple values 
* Removed unneeded function calls
(Just realized that I made two commits here, but let's just go with it)
* fixed sources CSV upload error
--  Introduced a bug in 234a7c5 😳
-- I'm glad the the linter caught it though 😊

Enabled unused-variable linting rule

---

.pylintrc

I propose leaving the remaining rules disabled. Please let me know what you think!

Leave remaining linting rules disabled

---

server/views/explorer/words.py
src/components/common/EditableWordCloudDataCard.js

fix explorer ngram download problem

---

src/resources/messages.js

Fixes #1909
Is this the correct link?

Fix footer discussion group link

---

config/webpack.base.config.js
doc/releases.md
package.json
src/config.js
src/explorerIndex.js
src/sourcesIndex.js
src/toolsIndex.js
src/topicsIndex.js

I think we agreed to just source the version from once place. I think `package.json` would be a natural place to store this.

Use "version" from package.json

---

server/views/admin/users.py

Delete user from frontend DB when an admin deletes user

---

doc/releases.md

Change deploy branch to main

---

src/components/explorer/results/QueryWordComparisonResultsContainer.js

Fixes #1924 
This reinstates the word cloud comparisons and updates the error message. It looks like the error stemmed from a change in the `results`. It appears to be an dict and all the code was expecting an array. I also removed the `OrderedWordCloud` in the case that there isn't a `rightQuery`. I don't see how this is possible and suspect that this is old code.
**2 Queries**
**More than two queries**
**Error message**

Fixed compare top words

---

server/util/tags.py
server/views/sources/__init__.py

Replaced 2016 with 2020 US Partisanship Sets

---

server/views/topics/apicache.py

Remove cache for topic_focal_sets_list

---

src/components/source/mediaSource/suggest/SourceSuggestion.js

Display suggested collection in suggested sources list

---

src/components/source/search/MediaPickerSourceSearchContainer.js
src/styles/sources/_search.scss

* Also, made it more mobile friendly
* Fixes #1944

Refactored sources media picker scss

---

src/components/source/mediaSource/SourceSplitStoryCountContainer.js
src/components/vis/AttentionOverTimeChart.js
src/lib/dateUtil.js

Fill gaps between days for story count in sources

---

server/auth.py
server/views/user.py

Correctly set user api key and profile when api is reset

---

src/components/common/statbar/Stat.js
src/components/common/statbar/StatBar.js
src/components/topic/platforms/PlatformDetailsInfo.js
src/components/topic/summary/TopicSummaryContainer.js
src/components/topic/versions/TopicVersionReadySummary.js

* layout updates to stats (centered, mobile layout)
Fixes #1912

Added seed query and collections to summary

---

server/views/topics/media.py

Add metadata to all media CSV download

---

src/components/topic/versions/TopicVersionReadySummary.js

First PR 🥳 🎊 🎉 
(Added one or statement, to address #1967 )

Fixing Missing 0 (#1967)

---

server/static/data/media-collection-tag-sets.json

US National is now default collection in explorer

---

README.md
src/components/source/collection/CollectionUploadSourceContainer.js
src/components/topic/TopicVersionInfo.js
src/components/topic/attention/FocusSetSelectorContainer.js
src/components/topic/platforms/PlatformDetailsInfo.js

Resolves #1966 and #1977! 
Edit for question: I had some notes to myself in the README that I had committed -- is there a way to exclude that on Github or should I un-commit locally?

Quick Bug Fixes

---

src/components/AppContainer.js
src/resources/messages.js

Update footer to include research consortium

---

src/components/explorer/results/QueryAttentionOverTimeResultsContainer.js

Default explorer attention chart to percentage

---

server/views/topics/__init__.py

Properly pass in media IDs for media inlink and outlink requests

---

config/webpack.prod.config.js
package-lock.json
package.json

Minify JS bundles with terser-webpack-plugin

---

src/components/topic/TopicStoryTable.js

Fix story table rendering when subtopics empty

---

package-lock.json
package.json
src/components/common/DataCard.js
src/components/common/hocs/DescribedDataCard.js
src/components/common/hocs/SummarizedVizualization.js
src/components/common/statbar/StatBar.js
src/components/explorer/home/Homepage.js
src/components/source/collection/CollectionDetailsContainer.js
src/components/source/collection/list/CountryCollectionListContainer.js
src/components/source/controlbar/SourceControlBar.js
src/components/source/homepage/FeaturedCollectionsContainer.js
src/components/source/homepage/SourcesHomepage.js
src/components/source/mediaSource/SourceDetailsContainer.js
src/components/topic/list/TopicPreviewList.js
src/components/topic/summary/TopicSummaryContainer.js
src/styles/app/_summarized_viz.scss
src/styles/sources/_featured_collections.scss
src/styles/topics/_topic_container.scss

* Updated data cards to use Material UI cards
* Started using material UI grid layout

Updated data card styles to material UI cards

---

server/views/sources/collectionedit.py
src/components/source/collection/CollectionUploadSourceContainer.js

Fix collection upload

---

src/components/common/CollapsingPanel.js
src/components/topic/platforms/ManagePlatformsContainer.js
src/components/topic/snapshots/foci/FocalSetDefinitionDetails.js
src/components/topic/snapshots/foci/FocusDefinition.js
src/components/topic/snapshots/foci/ManageFocalSetsContainer.js
src/components/topic/versions/TopicNewVersionContainer.js
src/components/topic/versions/TopicVersionContainer.js
src/components/topic/versions/VersionComparisonContainer.js
src/components/topic/wizard/EditTopicDataOptionsContainer.js
src/components/topic/wizard/TopicAdvancedForm.js
src/components/topic/wizard/TopicSeedDetailsForm.js
src/styles/topics/_focalset_definition_summary.scss
src/styles/topics/_manage_focal_sets.scss
src/styles/topics/_platform_builder.scss
src/styles/topics/_topic_info.scss

Update topic update and creation ux

---

src/components/source/SourceFeedTable.js
src/components/source/mediaSource/SourceFeedContainer.js
src/styles/sources/_feed_table.scss

* added in stub for sitemaps (only visible to admins)

Change source feeds to display by type (e.g. feed, podcast)

---

server/views/sources/feeds.py
src/actions/sources/sourceActions.js
src/components/source/SourceFeedTable.js
src/components/source/mediaSource/SourceFeedContainer.js
src/components/source/mediaSource/sitemaps/AbandonedIngestsTable.js
src/components/source/mediaSource/sitemaps/IngestCardActions.js
src/components/source/mediaSource/sitemaps/IngestCardFail.js
src/components/source/mediaSource/sitemaps/IngestCardPending.js
src/components/source/mediaSource/sitemaps/IngestCardSuccess.js
src/components/source/mediaSource/sitemaps/SourceSitemapsContainer.js
src/components/source/mediaSource/sitemaps/SuccessfulIngestsTable.js
src/lib/serverApi/sources.js

Added UI for sitemaps ingest per feed (hidden by admin role)

---

Procfile
server/static/data/release_history.json

not sure why it wasn't merge from the release branch

manually merge v3.22.1
