mediacloud/web-tools

src/components/explorer/results/QueryResultsContainer.js, src/components/explorer/results/QueryWordComparisonResultsContainer.js, src/reducers/explorer/topWordsComparison.js
If from the search button, act as if a new page mount,
If from the UI comparison widget, switch out the word clouds
=> fix for #868

requirements.txt, server/views/media_picker.py, server/views/media_search.py, src/components/common/mediaPicker/results/SourceResultsTable.js
When searching for media with `mediaList` we don't need to do a pool'ed call for mediaHealth to get the story count anymore (thanks to https://github.com/berkmancenter/mediacloud/issues/316).  Now results from that call come back with a `num_stories_90` value, which is the number of stories per day avg over the last 90 days.  We're using this in the media picker now to show the story count, and using the new `sort=num_stories` arg to sort by that automatically (so results from bigger/healthier matching sources bubble up to the top of the list)
=> Use new `num_stories_90` for media story count

.eslintrc, src/components/AppContainer.js, src/components/common/SourceList.js, src/components/common/composers/CsvDownloadNotifyContainer.js, src/components/source/collection/CollectionSourceListContainer.js, src/components/source/collection/CollectionUploadSourceContainer.js, src/components/topic/media/MediaStoriesContainer.js, src/components/topic/stories/InfluentialStoriesContainer.js, src/components/topic/summary/StoriesSummaryContainer.js, src/components/topic/words/WordStoriesContainer.js
The existing solution fires an alert notice at the top of the screen, rather than a move passive snackbar notification at the bottom of the screen.  This PR changes that.
More importantly, the existing solution includes a lot of repeated code, making it hard to refactor.  I would have to change 7-ish files that use this pattern in order to refactor it from a `Notice` to a `Snackbar` :-( To address this architecture problem I created a new wrapper class following the composition pattern.  This new `composeCsvDownloadNotifyContainer` can be used to wrap any class, and supplies a `notifyOfCsvDownload` method that the child can use.  Now if we want to change the implementation we can just change how that one method is using the underlying widgets.
=> refactor csv download notification

server/util/csv.py, server/util/tags.py, server/views/sources/__init__.py, server/views/sources/collection.py, server/views/sources/collectionedit.py, server/views/topics/__init__.py, server/views/topics/media.py
This tries to centralize the creation of source list CSVs (based on errors Anushka found).  Specifically, it uses the new `metadata` property that the API client adds to `mediaList` calls.  This lets us avoid having to walk through and parse the tags in the code here, because it does it for us in the API client code. I've also renamed some of the constants to more clearly indicate that they are lists of columns for CSV downloads/uploads.  
(Still waiting for https://github.com/berkmancenter/mediacloud/issues/190 to be resolved before we can treat media list calls in Topic Mapper the same way)
=> Centralize generation of source list CSV downloads

server/views/sources/collection.py, server/views/sources/feeds.py, src/components/source/SourceFeedTable.js, src/components/source/mediaSource/CreateSourceFeedContainer.js, src/components/source/mediaSource/EditSourceFeedContainer.js, src/components/source/mediaSource/form/SourceFeedForm.js, src/lib/serverApi/sources.js, src/reducers/sources/sources/selected/feed/info.js, src/resources/messages.js, src/styles/sources/_feed_table.scss
Hi again Cindy & Rahul,
As part of our cleanup (https://github.com/berkmancenter/mediacloud/issues/416), we want to:
1. Rename `feed_status` API JSON response field to `active` boolean, and
2. Rename `feed_type` API JSON response field to `type`.
*Before:*
```json
{
"feed_status": "active",
"feed_type": "syndicated"
}
```
*After:*
```json
{
"active": true,
"type": "syndicated"
}
```
(Admittedly I didn't even test those changes by running them because I'm not much of a frontender, those commits are basically just a careful find-and-replace, so I would be thankful if you could have a hard look into them.)
As detailed in https://github.com/berkmancenter/mediacloud/pull/421, could you:
1. Wait for us to release said PR (https://github.com/berkmancenter/mediacloud/pull/421),
2. Review, merge & …
=> Rename "feed_status" to "active" boolean, "feed_type" to "type"

Procfile, requirements.txt, run.sh
Large CSV downloads time out with network error for Anushka, e.g. from URL:
```
https://explorer.mediacloud.org/#/queries/search?q=[{%22label%22:%22Diseases%22,%22q%22:%22(diarrhea%20OR%20rota%20OR%20rotavirus)%20OR%20(hiv%20OR%20aids%20OR%20avahan%20OR%20naco%20OR%20antiretroviral)%20OR%20(malaria*)%20OR%20(pneumonia%20OR%20%22pneumococcal%20vaccine%22)%20OR%20(tuberculosis%20OR%20tb%20OR%20%22bcg%20vaccine%22)%20OR%20(polio%20OR%20IPV%20OR%20(OPV%20-ship%20-vessel%20-navy))%20OR%20(%22visceral%20leishmaniasis%22%20OR%20typhoid%20OR%20%20%22Lymphatic%20Filariasis%22%20OR%20Elephantiasis%20OR%20NTDs%20OR%20%22infectious%20disease%22%20OR%20%22infectious%20diseases%22%20OR%20%22Mass%20drug%20administration%22%20OR%20%22kala%20azar%22%20OR%20%22sandfly%22%20OR%20%22Acute%20Encephalitis%20Syn …
```
=> Increase worker timeout to 1 minute to allow large CSV downloads

src/components/common/hocs/AsyncContainer.js, src/lib/reduxHelpers.js
With this change, anything other than a HTTP 200 (OK) kills the action chain, and shows an error at a much lower widget level (rather than killing the whole UI) - via an `<ErrorBoundary>`. 
I'm a little nervous about the change to have the ErrorBoundary at a lower level (ie. around every single async widget), but I think it might help us fail more gracefully. Your thought?
=> stop processing after a 400 error

server/views/user.py, src/components/common/mediaPicker/MediaPickerDialog.js, src/components/user/SignupContainer.js, src/lib/serverApi/user.js
This removes the UI option to signup for a newsletter when creating user accounts. Simple change in a handful of files. Verified locally that I can still signup for a new account after this change.
=> Remove newsletter option on signup

package-lock.json, package.json, src/actions/storyActions.js, src/components/common/admin/HighlightedText.js, src/components/common/admin/story/StoryCachedContainer.js, src/components/common/admin/story/UpdateStoryContainer.js, src/components/explorer/results/QuerySampleStoriesResultsContainer.js, src/components/explorer/results/QueryTotalAttentionResultsContainer.js, src/components/explorer/results/drilldowns/SelectedStoryDrillDownContainer.js, src/components/topic/stories/StoryContainer.js, src/components/topic/stories/StoryUpdateContainer.js, src/reducers/story/info.js, src/reducers/topics/selected/story/info.js
For #1599.  This required refactoring the `selectStory` action to accept more than just and ID, so it has touchpoints in a few places. That action now accepts an object, so that we can pass the query string over to the `SelectedStoryDrillDownContainer`, which the uses the `logic-query-parser` library to translate the boolean logic query into a parsed tree we can extract strings from. The extraction isn't perfect, but I think it'll be a fine 80/20 that handles most queries.  I tried it on some reasonable complex one and it parsed pretty well.
=> highlight words matching queries for admins

src/components/explorer/results/drilldowns/SelectedStoryDrillDownContainer.js, src/components/topic/stories/StoryContainer.js, src/lib/stringUtil.js
This moves the query parsing/highlighting code into a shared library, and links it so that when you are in a Topic and look at the cached text it highlights the words from the query. I didn't use the `topic.pattern` regex because it seems to be in a different syntax that doesn't run in Javascript (perhaps it is Perl syntax?).
=> Highlight words matching topic query in cached text

README.md
I updated this to just link to the mongo instructions (the original `brew` ones are outdated.
=> Update instructions for installing MongoDB

requirements.txt, server/platforms/web_mediacloud.py, server/views/explorer/__init__.py, server/views/topics/__init__.py
This small change fixed #1862. This is mostly for cleanup, but does effect some story counts shown to users in non-research-critical places:
* source manager attention charts
* topic version seed query totals
Note that bumps the mediacloud-api library dependency up, so you'll have to `pip install` to get the latest library for it to work. Let me know how it looks and I'll merge.
=> Switch to new query data helper #1862

.pylintrc, .travis.yml
Fixes #1413 (we'll still need to enable the rules, but lets break that out into separate granular tasks).
Check out the checks that happen with this PR:
We can also think about running tests as part of the process too. I  ran them locally and a bunch of them failed though.
=> Added Travis config

src/lib/explorerUtil.js
Fixes #1915
Is it worth figuring out what the underlying cause of the UIDs being inconsistent? New ones appear to be ints, whereas when reloading from the page results in more UID-like identifiers.
N.B. Making this PR against `v3.14.x`.
=> Fix new explorer attention over time not appearing

src/store.js
Solution found on https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup.
Without this fix, we get the following error if redux tools are unavailable when developing locally:
```
Uncaught TypeError: Cannot read property 'apply' of undefined
at eval (redux.js:608)
at createStore (redux.js:87)
at configDevelopmentStore (store.js:32)
at getStore (store.js:51)
at reallyInitializeApp (index.js:51)
at initializeApp (index.js:170)
at eval (topicsIndex.js:28)
at Module../src/topicsIndex.js (app_js.05f18c2f0599af80ea91.js:34431)
at __webpack_require__ (app_js.05f18c2f0599af80ea91.js:20)
at eval (webpack:///multi_(:5000/webpack)-dev-server/client?:2:18)
```
=> Fix local development when redux tools unavailable

.flaskenv, requirements/common.txt, server/__init__.py, server/commands/__init__.py, server/database.py
First part of #1890
* Adds `flask sync-frontend-db`
* Adds `..flaskenv` for convenience in running flask command line
The new command calls the backend API to fetch users, diffs with the frontend, and removes users extra users.
N.B. PR will merge to `3.14.x`.
=> Added sync-frontend-db custom command

server/views/topics/provider.py
I noticed an error in the console and found that this default was being set to a list rather than a dict. I'm sure there were other issues with this, but one that I saw was that top stories weren't loading. 
FYI, I actually don't think that this bug ever made it to production.
=> Fixed default for _parse_optional_args

src/components/source/collection/ManageSourcesContainer.js
I noticed that errors were being through when formatting the "remove" string.
It's asking for a "count" variable on https://github.com/mitmedialab/MediaCloud-Web-Tools/blob/main/src/components/source/collection/ManageSourcesContainer.js#L45.
https://github.com/mitmedialab/MediaCloud-Web-Tools/blob/main/src/components/source/collection/ManageSourcesContainer.js#L132 shows an example of how it's done in the same file.
=> Fixed review sources "remove" label

src/components/source/collection/SelectCollectionContainer.js
Fixes #1937
In looking at the history, it seems like the collection ID was unset in refactoring the header to display the correct name. I removed this chunk of code, which indeed fixes the problem when clicking on the back button. I also clicked around a few times to sources, collections, etc. and the header all seemed correct to me.
This is a pretty old piece of code, so I wonder the problem it was originally intended to fix as addressed in subsequent upgrades.
=> Remove unset collection ID

.gitmodules
Hey Dennis,
I've moved the shared `email-templates` repo (used as a submodule) to our new org.
After pulling, make sure to run something along the lines of:
```
git submodule sync
git submodule update --init --recursive
```
=> Update submodule URL to shared email-templates repo

src/components/explorer/builder/QueryPickerContainer.js, src/components/explorer/results/QueryThemesResultsContainer.js, src/components/topic/snapshots/foci/builder/mediaType/MediaTypeStoryCountsPreviewContainer.js, src/components/topic/snapshots/foci/builder/nyttheme/NytThemeStoryCountsPreviewContainer.js, src/components/topic/snapshots/foci/builder/partisanship/PartisanshipStoryCountsPreviewContainer.js, src/components/topic/snapshots/foci/builder/topCountries/TopCountriesStoryCountsPreviewContainer.js, src/lib/colorUtil.js
This implements an idea we discussed on a call - to allow quick comparisons of explorer queries across US political collections or years. I think this will help a lot in my teaching, and for demos to reveal some of the possible axes of comparative analysis. Also this sets up a generic approach to adding more items to this menu, based on researcher needs.
New 3-dot menu next to "Add Query" in Explorer opens the menu with 2 options (for now):
Picking either pops up an appropriate confirmation dialog:
Clicking "OK" replaces the queries as described and runs the queries right away:
Notes:
* This is implemented via the URL, not via pushing the new queries to state (because that seemed easier to me). I thought that would make the back button work better, but it doesn't :-( Ideas on a better …
=> add shortcuts for quick query comparisons

config/app.config.template, server/__init__.py, server/auth.py, server/util/tags.py
Adds the ability to use different mediacloud API backends by specifying a **MEDIA_CLOUD_API_URL** environment variable.
Fixes https://github.com/mediacloud/web-tools/issues/1958
=> Allow use of different mediacloud api backends

.eslintrc, README.md, package-lock.json, package.json, src/components/AppContainer.js, src/components/common/EditableWordCloudDataCard.js, src/components/common/MetadataPickerContainer.js, src/components/common/apiConsole/SwaggerContainer.js, src/components/explorer/builder/QueryPickerContainer.js, src/components/explorer/home/Homepage.js, src/components/source/collection/SelectCollectionContainer.js, src/components/source/mediaSource/suggest/SourceSuggestion.js, src/components/topic/platforms/CreatePlatformContainer.js, src/components/topic/platforms/EditPlatformContainer.js, src/components/topic/platforms/builder/PlatformWizard.js, src/components/user/LoginFormContainer.js, src/components/util/topicUtil.js, src/components/vis/AttentionOverTimeChart.js, src/lib/dateUtil.js
Adds the following:
* `npm run lint_fix`
* `npm run lint`
* pre-commit hook for that runs `npm run lint` before commits
* upgraded linting packages
* fixed linting errors
@deblnia -- this fixes the problem with running linting and a command to auto-fix linting errors (if possible)
=> Added fixed JS linting and added commands to run linting

src/components/topic/attention/FocusSetSelectorContainer.js, src/components/topic/controlbar/FocusSelector.js, src/components/topic/words/FociWordComparison.js, src/components/vis/AttentionOverTimeChart.js
Very small topic mapper updates:
* added "dated" to attention chart
* disable word comparison if none
=> Added "dated" to attention chart, disable word comparison if none
